apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huge-feedback.fullname" . }}
type: Opaque
stringData:
  config.edn: |-
    {:huge-feedback.apis.gitlab/config     {:huge-feedback.apis.gitlab/base-url   "{{.Values.config.gitlabUrl}}"
                                            :huge-feedback.apis.gitlab/project-id {{.Values.config.gitlabProjectId}}
                                            :huge-feedback.apis.gitlab/token      "{{.Values.config.gitlabToken}}"}
     :huge-feedback.config/use-cors-proxy? true
     :huge-feedback.config/num-pipelines-to-show {{.Values.config.pipelinesToShow}}
     :huge-feedback.config/server-port 80}